/* Generated by scripts/compile-messages.mjs — do not edit. */
export const SEARCH_MESSAGES = {
  "search.jlixAsOfMismatch": "[jp-local-gov-id] JLIX asOf ({searchAsOf}) differs from prefectures asOf ({prefecturesAsOf})",
  "search.missingThreeGramShard": "Dataset searchNgramShards missing 3-gram shard \"{key}\"",
  "search.missingTwoGramRegion": "Dataset searchNgramShards missing 2-gram region \"{key}\"",
  "search.nPositiveInteger": "n must be a positive integer",
  "search.shardCountPositiveInteger": "shardCount must be a positive integer",
  "search.unrecognizedPath": "Unrecognized search index path for dataset: {relativePath}",
} as const;

export type SearchMessageKey = keyof typeof SEARCH_MESSAGES;
