/* Generated by scripts/compile-messages.mjs — do not edit. */
export const ENCODE_MESSAGES = {
  "binary.asOfExceedsU1": "asOf exceeds u1 length",
  "binary.jldt.encodeSizeMismatch": "Internal encode size mismatch (JLDT)",
  "binary.jlix.encodeSizeMismatch": "Internal encode size mismatch (JLIX)",
  "binary.jlpr.encodeSizeMismatch": "Internal encode size mismatch (JLPR)",
  "binary.recordCountExceedsU2": "record_count exceeds u2",
  "binary.versionOutOfU1": "version out of u1 range: {version}",
  "data.unknownPrefectureCode": "Unknown prefecture code: {code}",
} as const;

export type EncodeMessageKey = keyof typeof ENCODE_MESSAGES;
